config/routes.rb
Rails.application.routes.draw do
  
  concern :with_datatable do
    post 'datatable', on: :collection
  end

  resources :types
  resources :users
  resources :attendance_lists, concerns: [:with_datatable]
  resources :status
  root :to =>'attendance_lists#index'

  get '/reger' => 'users#reger'
  get '/pt' => 'users#trainees'
  
  devise_for :admins, controllers: {:registrations => "admins/registrations", :sessions => "admins/sessions"}, :path_prefix => 'my'
  resources :admins
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/edit.html.erb
<%= render 'shared/navbar'%>

<div class = "container pb-3 pt-4">
  <h3><span class="badge badge-pill badge-warning">Editar Administrador</span></h3>

  <%= form_for(@admin) do |f| %>
    <% if @admin.errors.full_messages.empty? %>
      <div class="py-4"></div> <%# Div apenas para dar espaco %>
    <% else %>
      <% @admin.errors.full_messages.each do |e| %>
        <span class="badge badge-danger my-3"> <%= e %> </span>
      <% end %>
    <% end %>

    <div class="field form-group">
      <%= f.label :email %>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :password, "Senha" %> <i>(deixe em branco se não quiser mudar)</i>
      <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :password_confirmation, "Confirme sua senha" %>
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
    </div>

    <div class="actions w-100 d-flex justify-content-between my-5">
      <%= link_to 'Voltar', :back, class: "btn btn-secondary px-5" %>
      <%= f.submit "Salvar", class: "btn btn-primary px-5" %>
    </div>
    
    <div class="actions w-100 d-flex justify-content-center my-5">
      <%= link_to "Apagar Administrador", admin_registration_path(@admin), 
                                          data: { confirm: "Are you sure?" }, 
                                          method: :delete, class: "btn btn-danger" %>
    </div>
  <% end %>

</div>

app/views/admins/index.html.erb
<%= render 'shared/navbar'%>

<p id="notice"><%= notice %></p>
<div class = "container pb-3 pt-4">
   <h3><span class="badge badge-pill badge-warning">Administradores</span></h3>
  <br>

  <table class ="table table-responsive-sm table-hover" >
    <thead>
      <tr>
        <th colspan="3">Email</th>
      </tr>
    </thead>

    <tbody>
      <% @admins.order(:email).each do |a| %>
        <tr>
            <td class="<%= 'text-primary' if a == current_admin %>"> <%= a.email %> </td>
            <td> <%= link_to 'Editar', edit_admin_path(a), class: 'text-warning' %> </td>
            <td> <%= link_to 'Excluir', admin_registration_path(a), method: :delete, data: { confirm: 'Are you sure?' }, class:"text-danger" %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <div class="d-flex w-100 justify-content-center my-4">
    <%= link_to 'Novo', new_admin_path, class: 'btn btn-primary mr-3 px-5' %>
  </div>
</div>

app/views/admins/new.html.erb
<%= render 'shared/navbar'%>

<div class = "container pb-3 pt-4">
  <h3><span class="badge badge-pill badge-warning">Novo Administrador</span></h3>
    
  <%= form_for(@admin) do |f| %>
    <% if @admin.errors.full_messages.empty? %>
      <div class="py-4"></div> <%# Div apenas para dar espaco %>
    <% else %>
      <% @admin.errors.full_messages.each do |e| %>
        <span class="badge badge-danger my-3"> <%= e %> </span>
      <% end %>
    <% end %>

    <div class="field form-group">
      <%= f.label :email %>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :password, "Senha" %>
      <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :password_confirmation, "Confirme sua senha" %>
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
    </div>

    <div class="actions w-100 d-flex justify-content-between my-5">
      <%= link_to 'Voltar', :back, class: "btn btn-secondary px-5" %>
      <%= f.submit "Criar", class: "btn btn-primary px-5" %>
    </div>
  <% end %>

</div>