config/routes.rb
Rails.application.routes.draw do
  
  concern :with_datatable do
    post 'datatable', on: :collection
  end

  resources :types
  resources :users
  resources :attendance_lists, concerns: [:with_datatable]
  resources :status
  root :to =>'attendance_lists#index'

  get '/reger' => 'users#reger'
  get '/pt' => 'users#trainees'
  
  devise_for :admins, controllers: {:registrations => "admins/registrations", :sessions => "admins/sessions"}, :path_prefix => 'my'
  resources :admins
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance_list.rb
class AttendanceList < ApplicationRecord
    belongs_to :type
    has_many :status, dependent: :destroy 
    has_many :user, through: :status
     
    validates :data, presence: true
end

app/controllers/attendance_lists_controller.rb
class AttendanceListsController < ApplicationController
  before_action :set_attendance_list, only: [:show, :edit, :update, :destroy]
  before_action :select_type, only: [:new, :edit, :update, :create]

  skip_before_action :verify_authenticity_token

  # GET /attendance_lists
  # GET /attendance_lists.json
  def index
  end

  def datatable
    render json: AttendanceListDatatable.new(params)
  end

  # GET /attendance_lists/1
  # GET /attendance_lists/1.json
  def show
  end

  # GET /attendance_lists/new
  def new
    @attendance_list = AttendanceList.new
    
    @users = User.all.where(active: true).order(nome: :asc)
  end

  # GET /attendance_lists/1/edit
  def edit
  end

  # POST /attendance_lists
  # POST /attendance_lists.json
  def create
    @attendance_list = AttendanceList.new(attendance_list_params)
      if @attendance_list.save 
      redirect_to new_status_path
     else 
      render :new
    end

  end


  # PATCH/PUT /attendance_lists/1
  # PATCH/PUT /attendance_lists/1.json
  def update
  
      if @attendance_list.update(attendance_list_params)
        redirect_to edit_status_path(@attendance_list)
       
      else
        render :edit 
      end
   
  end

  # DELETE /attendance_lists/1
  # DELETE /attendance_lists/1.json
  def destroy
    @attendance_list.destroy
    respond_to do |format|
      format.html { redirect_to attendance_lists_url, notice: 'Attendance list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def select_type
      @select_type = Type.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_attendance_list
      @attendance_list = AttendanceList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendance_list_params
      params.require(:attendance_list).permit(:data, :description, :type_id)
    end
end

app/helpers/attendance_lists_helper.rb
module AttendanceListsHelper
end

app/views/attendance_lists/_form.html.erb
<%= form_with(model: attendance_list, local: true) do |form| %>
  
  <% if attendance_list.errors.full_messages.empty? %>
    <div class="py-4"></div> <%# Div apenas para dar espaco %>
  <% else %>
    <% attendance_list.errors.full_messages.each do |e| %>
      <span class="badge badge-danger my-3"> <%= e %> </span>
    <% end %>
  <% end %>

  <div class= "form-row">
    <div class="field col">
      <%= form.label :type_id, "Tipo da Chamada"%>
      <%= collection_select(:attendance_list, :type_id,  @select_type, :id, :name, {}, {:class=>'form-control'})%>
    </div>
  </div>
  
  <div class="my-3">
    <%= link_to 'Criar novo tipo de chamada', new_type_path, class: 'btn btn-success px-4 mb-2'%>
    <%= link_to 'Ver todos os tipos', types_path, class: 'btn btn-primary px-3 mb-2'%>
  </div>

  <div class = "row">
    <div class="field col">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class = "row">
    <div class="field col mt-2">
      <%= form.label :data %>

      <%= form.date_field :data, class: 'form-control', strftime: "dd/mm/yyyy" %>

    </div>
  </div>

  <br>
  <div class="actions d-flex flex-wrap justify-content-between my-4">
    <%= link_to 'Voltar', attendance_lists_path(format: [:html, :json]), class: 'btn btn-secondary my-1 px-4'%>
    <%= form.submit 'Avançar', class: "btn btn-primary px-4" if current_page?(new_attendance_list_path)%>
    <%= form.submit 'Editar Lista de Chamada', class: "btn btn-primary my-1 px-4" if !current_page?(new_attendance_list_path) %>
    <%= link_to 'Exibir lista de Chamada', @attendance_list, class: 'btn btn-info my-1 px-4' if !current_page?(new_attendance_list_path)%>
  </div>
<% end %>

app/views/attendance_lists/edit.html.erb
<%= render 'shared/navbar'%>

<div class = "container pb-3 pt-4">
    <h3><span class="badge badge-pill badge-success">Editar lista de Chamada</span></h3>
    <%= render 'form', attendance_list: @attendance_list %>
</div>

app/views/attendance_lists/index.html.erb
<%= render 'shared/navbar'%>
<div class = "container pb-3 pt-4">
  <h3><span class="badge badge-pill badge-success">Listas de Chamada</span></h3>
  <br>

    <table id="att_lists-datatable" style="width:100%" class ="table table-striped table-hover" data-source="<%= datatable_attendance_lists_path(format: :json) %>">
    <thead>
      <tr>
        <th>Data</th>
        <th>Tipo</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
    </tbody>
  </table>

  <div class="d-flex w-100 justify-content-center my-4">
    <%= link_to 'Nova lista de chamada', new_attendance_list_path, class: 'btn btn-lg btn-success mr-3 px-4' %>
  </div>
</div>

app/views/attendance_lists/new.html.erb
<%= render 'shared/navbar'%>

<div class = "container pb-3 pt-4">
    <h3><span class="badge badge-pill badge-success">Nova lista de Chamada</span></h3>
    
    <%= render 'form', attendance_list: @attendance_list %>
</div>

app/views/attendance_lists/show.html.erb
<p id="notice"><%= notice %></p>	

<%= render 'shared/navbar'%>

<div class = "container pb-3 pt-4">
	<p>
	<strong>Data:</strong>
	<%= @attendance_list.data %>
	</p>

	<p>
	<strong>Descrição:</strong>
	<%= @attendance_list.description %>
	</p>

	<table class ="table table-responsive-sm table-responsive-md table-hover">
		<thead>
		<tr>
			<th>Nome</th>
			<th>Email</th>
			<th>Estado</th>
		</tr>
		</thead>
			
		<% @attendance_list.status.each do |dd|  %> 
			<tr>
				<td><%= User.find(dd.user_id).nome  %></td>
				<td><%= User.find(dd.user_id).email  %></td>
				<td> 
					<% if dd.state == "Falta" %>
						<span class="badge badge-pill badge-danger mr-1 d-block">Falta</span>
					<% end %>
					<% if dd.state == "Presente" %>
						<span class="badge badge-pill badge-success mr-1 d-block">Presente</span>
					<% end %>
					<% if dd.state == "Falta Justificada" %>
						<span class="badge badge-pill badge-warning mr-1 d-block">Falta Justificada</span>
					<% end %>
					<% if dd.state == "Atraso Justificado" %>
						<span class="badge badge-pill badge-dark mr-1 d-block">Atraso Justificado</span>
					<% end %>
				</td>
				
			</tr>	
		<% end %> 
	</table>

	<%= link_to 'Editar', edit_attendance_list_path(@attendance_list), class: "float-right btn btn-primary mr-3 px-4" %> 
	<%= link_to 'Voltar', :back, class: "btn btn-secondary mr-3 px-4" %>
</div>