config/routes.rb
Rails.application.routes.draw do
  
  concern :with_datatable do
    post 'datatable', on: :collection
  end

  resources :types
  resources :users
  resources :attendance_lists, concerns: [:with_datatable]
  resources :status
  root :to =>'attendance_lists#index'

  get '/reger' => 'users#reger'
  get '/pt' => 'users#trainees'
  
  devise_for :admins, controllers: {:registrations => "admins/registrations", :sessions => "admins/sessions"}, :path_prefix => 'my'
  resources :admins
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_many :status, dependent: :destroy 
	has_many :attendance_list, through: :status
	 
	has_and_belongs_to_many :types

 	validates :nome, presence: true
 	validates :email, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :stop_inactive_user, only: [:show, :edit, :update]

  # GET /users
  # GET /users.json
  def index
    @core = params[:core]

    if @core.nil?
      @users = User.all.where(active: true)
    else
      @users = User.all.where(active: true).where(nucleo: @core)
    end
  end

  #GET /pt
  def trainees
    @users = User.all.where(active: true)
  end 

  #GET /reger
  def reger
    @users = User.all.where(active: true)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @types = @user.types
  end

  # GET /users/new
  def new
    @user = User.new
  end
  
  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path}
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path}
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  # Usuario nunca são apagados do banco, apenas tornam-se inativos
  def destroy
    @user.update({nome: @user.nome, email: @user.email, membro: @user.membro, nucleo: @user.nucleo, active: false})
    respond_to do |format|
      format.html { redirect_to users_path}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def stop_inactive_user
      if @user.active == false then redirect_to :root, alert: "Erro! Usuário Inativo." end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nome, :email, :membro, :nucleo)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  
  <% if user.errors.full_messages.empty? %>
    <div class="py-4"></div> <%# Div apenas para dar espaco %>
  <% else %>
    <% user.errors.full_messages.each do |e| %>
      <span class="badge badge-danger my-3"> <%= e %> </span>
    <% end %>
  <% end %>

  <div class= "row">
    <div class="field col">
      <%= form.label :nome %>
      <%= form.text_field :nome, class: "form-control" %>
    </div>

    <div class="field col">
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control"%>
    </div>
  </div>

  <div class = "d-flex mt-4">
      <div class="field col form-group">
        <%= form.check_box :membro, class: "form-check-label" %>
        <%= form.label :membro %>
      </div>

      <%# Selecao de nucleo %>
      <div id="choose_core" style="display:none;" class="col form-group">
        <%= form.label :nucleo, "Escolha o núcleo do usuário" %>
        <%= form.select :nucleo, ['nenhum', 'NDP', 'NOE', 'NUT', 'NAT', 'NUMAR', 'PRES'], {}, class: "form-control" %>
      </div>

      <%# JAVASCRIPT PARA APARECER OU APAGAR SELECAO DE NUCLEO SE USER FOR MEMBRO OU NAO %>
      <script type="text/javascript">
        var checkbox = document.getElementById('user_membro');
        var details_div = document.getElementById('choose_core');

        if(checkbox.checked) { // Para aparecer o select quando editar um membro
          details_div.style['display'] = 'block';
        }

        checkbox.onchange = function() {
          if(this.checked) {
            details_div.style['display'] = 'block';
          } else {
            details_div.style['display'] = 'none';
            document.getElementById('user_nucleo').value = 'nenhum'; // Para Trainee sempre serem de nenhum nucleo
          }
        };
      </script>
      <%# END JAVASCRIPT %>
  </div>

  <div class="actions d-flex justify-content-between my-5">
    <%= link_to 'Voltar', :back, class: "btn btn-secondary px-5" %>
    <%= form.submit 'Criar', class: "btn btn-primary buttons-new px-5" if current_page?('/users/new')%>
    <%= form.submit 'Atualizar', class: "btn btn-primary buttons-new px-4" if !current_page?('/users/new')%>
  </div>

<% end %>

app/views/users/edit.html.erb
<%= render 'shared/navbar'%>

<div class = "container pb-3 pt-4">
     <h3><span class="badge badge-pill badge-success">Editar Membro/Trainee</span></h3>

    <%= render 'form', user: @user %>
</div>

app/views/users/index.html.erb
<%= render 'shared/navbar'%>

<p id="notice"><%= notice %></p>
<div class = "container pb-3 pt-4">

  <h3>
  <%= link_to 'Todos', users_path, class: 'badge badge-pill badge-success' if @core.nil? %>
  <%= link_to 'Todos', users_path, class: 'badge badge-pill badge-secondary' if !@core.nil? %>

  <%= link_to 'NDP', users_path(core: "NDP"), class: 'badge badge-pill badge-success' if @core == "NDP" %>
  <%= link_to 'NDP', users_path(core: "NDP"), class: 'badge badge-pill badge-secondary' if @core != "NDP" %>

  <%= link_to 'NUT', users_path(core: "NUT"), class: 'badge badge-pill badge-success' if @core == "NUT" %>
  <%= link_to 'NUT', users_path(core: "NUT"), class: 'badge badge-pill badge-secondary' if @core != "NUT" %>

  <%= link_to 'NOE', users_path(core: "NOE"), class: 'badge badge-pill badge-success' if @core == "NOE" %>
  <%= link_to 'NOE', users_path(core: "NOE"), class: 'badge badge-pill badge-secondary' if @core != "NOE" %>

  <%= link_to 'NAT', users_path(core: "NAT"), class: 'badge badge-pill badge-success' if @core == "NAT" %>
  <%= link_to 'NAT', users_path(core: "NAT"), class: 'badge badge-pill badge-secondary' if @core != "NAT" %>
  
  <%= link_to 'NUMAR', users_path(core: "NUMAR"), class: 'badge badge-pill badge-success' if @core == "NUMAR" %>
  <%= link_to 'NUMAR', users_path(core: "NUMAR"), class: 'badge badge-pill badge-secondary' if @core != "NUMAR" %>

  <%= link_to 'Trainees', users_path(core: "nenhum"), class: 'badge badge-pill badge-success' if @core == "nenhum" %>
  <%= link_to 'Trainees', users_path(core: "nenhum"), class: 'badge badge-pill badge-secondary' if @core != "nenhum" %>

  <%= link_to 'PRES', users_path(core: "PRES"), class: 'badge badge-pill badge-success' if @core == "PRES" %>
  <%= link_to 'PRES', users_path(core: "PRES"), class: 'badge badge-pill badge-secondary' if @core != "PRES" %>
  </h3>

  <br>
  <table class ="table table-responsive-sm table-responsive-md table-striped" >
    <thead>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Membro</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.order(:nome).each do |user| %>
        <tr>
          <td><%= user.nome %></td>
          <td><%= user.email %></td>
          <td>
            <% if user.membro == true %>
              <span class="badge badge-success mr-1 d-block">Membro</span>
            <% end %>
            <% if user.membro == false %>
              <span class="badge badge-danger mr-1 d-block">Trainee</span>
            <% end %>
        </td>
          <td><%= link_to 'Histórico', user_path(user), class: 'text-primary btn-sm' %></td>
          <td><%= link_to 'Editar', edit_user_path(user), class: 'text-primary btn-sm' %></td>
          <td><%= link_to 'Excluir', user, method: :delete, data: { confirm: 'Are you sure?' }, class:"text-danger btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="d-flex w-100 justify-content-center my-4">
    <%= link_to 'Novo', new_user_path, class: 'btn btn-primary mr-3 mb-4 px-5' %>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'shared/navbar'%>

<div class = "container pb-3 pt-4">
    <h3><span class="badge badge-pill badge-success">Novo Membro/Trainee</span></h3>

    <%= render 'form', user: @user %>
</div>

app/views/users/reger.html.erb
<%= render 'shared/navbar'%>

<div class = "container pb-3 pt-4">
   <h3><span class="badge badge-pill badge-success">Lista de Membros</span></h3>
  <br>

  <table class ="table table-responsive-sm table-responsive-md table-hover" >
    <thead>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Membro</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.order(:nome).each do |user| %>
        <% if user.membro == true %>
            <tr>
              <td><%= user.nome %></td>
              <td><%= user.email %></td>
              <td>
                  <span class="badge badge-pill badge-success mr-1 d-block">Membro</span>
              </td>
              <td><%= link_to 'Histórico', user_path(user), class: 'text-primary btn-sm' %></td>
              <td><%= link_to 'Editar', edit_user_path(user), class: 'text-primary btn-sm' %></td>
              <td><%= link_to 'Excluir', user, method: :delete, data: { confirm: 'Are you sure?' }, class:"text-danger btn-sm" %></td>
            </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <div class="d-flex w-100 justify-content-center my-4">
    <%= link_to 'Novo', new_user_path, class: 'btn btn-primary mr-3 px-5' %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'shared/navbar' %>

<div class = "container pb-3 pt-4">

  <h1 class="text-primary">
    <%= @user.nome %> 
    
    <% if @user.membro %>
    <span class="badge badge-success">M</span>
    <% else %>
    <span class="badge badge-danger">T</span>
    <% end %>

    <% case @user.nucleo %>
      <% when "NDP" %>  
      <span class="badge badge-info">NDP</span>
      <% when "NUT" %>  
      <span class="badge badge-dark">NUT</span>
      <% when "NOE" %>  
      <span class="badge badge-warning">NOE</span>
      <% when "NAT" %>  
      <span class="badge badge-primary">NAT</span>
      <% when "NUMAR" %>  
      <span class="badge badge-light">NUMAR</span>
      <% when "PRES" %>  
      <span class="badge badge-warning">PRES</span>
      <% else %>  
      <span class="badge badge-danger">Trainee</span>
    <% end %>

  </h1>

  <h5><%= @user.email %></h5>

  <table class ="table table-responsive-sm table-responsive-md table-hover table-bordered my-4" >
    <thead>
      <tr>
        <th>Tipos de Chamadas que Participa</th>
        <th>Presenças</th>
        <th>Faltas</th>
        <th>Faltas Justificadas</th>
        <th>Atrasos Justificados</th>
        <th><strong>Total</strong></th>
      </tr>
    </thead>

    <tbody>
      <% total_p = 0 %>
      <% total_f = 0 %>
      <% total_fj = 0 %>
      <% total_aj = 0 %>
      <% total_row = 0 %>

      <% @types.each do |type| %>
        <tr>
          <td><%= type.name %></td>

          <% ids = type.attendance_list_ids %>

          <td><%= p = Status.all.select{ |s| ids.include?(s.attendance_list_id) && s.user_id == @user.id && s.state == "Presente" }.count %></td>
          <td><%= f = Status.all.select{ |s| ids.include?(s.attendance_list_id) && s.user_id == @user.id && s.state == "Falta" }.count %></td>
          <td><%= fj = Status.all.select{ |s| ids.include?(s.attendance_list_id) && s.user_id == @user.id && s.state == "Falta Justificada" }.count %></td>
          <td><%= aj = Status.all.select{ |s| ids.include?(s.attendance_list_id) && s.user_id == @user.id && s.state == "Atraso Justificado" }.count %></td>
          <td><%= row = p + f + fj + aj %></td>
        <tr>

        <% total_p += p %>
        <% total_f += f %>
        <% total_fj += fj %>
        <% total_aj += aj %>
        <% total_row += row %>
      <% end %>

      <tr class="table-active">
          <td><strong>Total</strong></td>

          <td><%= total_p %></td>
          <td><%= total_f %></td>
          <td><%= total_fj %></td>
          <td><%= total_aj %></td>
          <td><%= total_row %></td>
        <tr>

    </tbody>
  </table>

  <div class="d-flex justify-content-between my-5">
    <%= link_to 'Voltar', :back, class: "btn btn-secondary px-5" %>
    <%= link_to 'Editar Usuário', edit_user_path(@user), class: "btn btn-primary buttons-new px-4" %>
  </div>
</div>

app/views/users/trainees.html.erb
<%= render 'shared/navbar'%>

<div class = "container pb-3 pt-4">
   <h3><span class="badge badge-pill badge-success">Lista de Trainees</span></h3>
    <br>

  <table class ="table table-responsive-sm table-responsive-md table-hover" >
    <thead>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Membro</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.order(:nome).each do |user| %>
        <% if user.membro == false %>
            <tr>
              <td><%= user.nome %></td>
              <td><%= user.email %></td>
              <td>
                <% if user.membro == false %>
                  <span class="badge badge-pill badge-danger mr-1 d-block">Trainee</span>
                <% end %>
              </td>
              <td><%= link_to 'Histórico', user_path(user), class: 'text-primary btn-sm' %></td>
              <td><%= link_to 'Editar', edit_user_path(user), class: 'text-primary btn-sm' %></td>
              <td><%= link_to 'Excluir', user, method: :delete, data: { confirm: 'Are you sure?' }, class:"text-danger btn-sm" %></td>
            </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <div class="d-flex w-100 justify-content-center my-4">
    <%= link_to 'Novo', new_user_path, class: 'btn btn-primary mr-3 px-5' %>
  </div>
</div>