config/routes.rb
Rails.application.routes.draw do
  
  concern :with_datatable do
    post 'datatable', on: :collection
  end

  resources :types
  resources :users
  resources :attendance_lists, concerns: [:with_datatable]
  resources :status
  root :to =>'attendance_lists#index'

  get '/reger' => 'users#reger'
  get '/pt' => 'users#trainees'
  
  devise_for :admins, controllers: {:registrations => "admins/registrations", :sessions => "admins/sessions"}, :path_prefix => 'my'
  resources :admins
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class = "container">
        <%= link_to image_tag("Logo_CJR.png", border: 0, width: "75px", height: "100%", alt: "Chamada", padding: 0, margin: 0 ), attendance_lists_path(format: [:html, :json]) , class: 'navbar-brand' , id: "something" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mx-2">
            <li class="nav-item">
                <%= link_to "Inicio", attendance_lists_path(format: [:html, :json]), class: "nav-link" if !request.env['PATH_INFO'].include?('/attendance_lists') && !current_page?('/') %>
                <%= link_to "Inicio", attendance_lists_path(format: [:html, :json]), class: "text-primary nav-link active" if request.env['PATH_INFO'].include?('/attendance_lists') || current_page?('/') %>
            </li>
            <li class="nav-item">
                <%= link_to "Lista de Membros", reger_path, class: "nav-link" if !current_page?('/reger')%>
                <%= link_to "Lista de Membros", reger_path, class: "text-primary nav-link active" if current_page?('/reger')%>
            </li>
            <li class="nav-item">
                <%= link_to "Lista de Trainees", pt_path, class: "nav-link" if !current_page?('/pt')%>
                <%= link_to "Lista de Trainees", pt_path, class: "text-primary nav-link active" if current_page?('/pt')%>
            </li>
            <li class="nav-item">
                <%= link_to "Todos / Núcleos", users_path, class: "nav-link" if !request.env['PATH_INFO'].include?('/users')%>
                <%= link_to "Todos / Núcleos", users_path, class: "text-primary nav-link active" if request.env['PATH_INFO'].include?('/users')%>
            </li>
            <li class="nav-item">
                <%= link_to "Administradores", admins_path, class: "nav-link" if !request.env['PATH_INFO'].include?('/admins')%>
                <%= link_to "Administradores", admins_path, class: "text-warning nav-link active" if request.env['PATH_INFO'].include?('/admins')%>
            </li>
            </ul>
            <!--
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar por Data (em Breve)" aria-label="Pesquisar Membro">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisar</button>
            </form>
            -->
             <div class="nav-item">
                <%= link_to 'Sair', destroy_admin_session_path, method: :delete, class: "text-danger" %>
            </div>
        </div>
    </div>
</nav>

<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>

<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>